apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
  labels:
    name: php-apache-service
    app: php-apache
spec:
  ports:
  - name: root
    port: 80
    targetPort: 80
  selector:
    app: php-apache
  type: LoadBalancer