apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: cloudiqreg.azurecr.io/php-apache-sample
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: ciq-acr-config-secret